### PR TITLE
Move files to lib/ to make whitelisting easier

### PR DESCRIPTION
**Pull request by locks**
I'm not sure about `/lib/diff.js` since it seems to be an executable?

### CODE REVIEW

**Comment by stefanpenner** [comment]
👍  

@hjdivad r?

**Comment by hjdivad** [comment]
@locks @stefanpenner we can probably remove the diff stuff entirely.  I don't think it's used any longer.

**Comment by locks** [comment]
@hjdivad I've pushed a commit removing the diff files. Let me know if I got it right, so I can squashy squash.

**Comment by hjdivad** [comment]
@locks LGTM, squashy away 👍

**Comment by stefanpenner** [comment]
:shipit:

**Comment by locks** [comment]
👌

**Pull request merged**
